apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cobra-python
  janus-idp.io/tekton: cobra-python
  backstage.io/kubernetes-id: cobra-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cobra-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
